"""empty message

Revision ID: 3aded7344cb8
Revises: 901d24f8c093
Create Date: 2022-05-29 23:51:37.774325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aded7344cb8'
down_revision = '901d24f8c093'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('need_venue', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('venue_description', sa.String(), nullable=True))
    op.add_column('Venue', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('genres', sa.String(length=120), nullable=True))
    op.add_column('Venue', sa.Column('need_talent', sa.Boolean(), nullable=True))
    op.add_column('Venue', sa.Column('talent_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'talent_description')
    op.drop_column('Venue', 'need_talent')
    op.drop_column('Venue', 'genres')
    op.drop_column('Venue', 'website_link')
    op.drop_column('Artist', 'venue_description')
    op.drop_column('Artist', 'need_venue')
    op.drop_column('Artist', 'website_link')
    # ### end Alembic commands ###
